### ISSUE TITLE
Consider removing `remove` method from the driver

### ISSUE THREAD

**Issue by dankleiman** [taganaka/redis-bloomfilter#6]
I recently came across a nasty bug that I believe is a combination of having a `remove` option and the underlying lua implementation that scales the bloomfilter and increments the counter on each write function call.

Even if you roll the dice with an error rate, `remove` in a bloomfilter that is flipping bits seems unsafe. Any time the same bit gets flipped to 1 by two different pieces of data, you risk removing **both pieces** of data if you subsequently remove **either one** by setting that bit back to 0.

But with scaling in the mix, the issue is even thornier. Since we are [incrementing the count each time the `insert` function is called](https://github.com/taganaka/redis-bloomfilter/blob/master/lib/bloomfilter_driver/lua.rb#L45), any operation -- insert, remove, or even an add call with duplicate data -- will increment the counter. This accelerates the count that determines whether or not a new index, i.e. a new redis key, should be added and in turn creates unintended scaling.

What's more, you get unintended corruption and don't actually remove data if you have started added new keys in your scaled bloom filter, but try to remove something that was added to a previous key. 

You don't know deterministically which key any one piece of data was written to. And you only ever add to the latest key.

Here's an example:

```
# initialize with a fixed size
size = 10
name = 'test'

# set up more than size-amount of data
ids = []
12.times { ids << SecureRandom.uuid }

bf = Redis::Bloomfilter.new(
              :size       => size,
              :error_rate => 0.001, # 0.1%
              :key_name   => name,
              :driver     => 'lua',
              :redis      => $redis
            )

# insert over size so we generate 2 buckets
ids.each { |d| bf.insert(d) }

# verify bucket count
[15] pry(main)> $redis.keys('test*')
=> ["test:1", "test:2", "test:count"]

# verify insert count (lua code increments count before each insert)
[16] pry(main)> $redis.get("test:count")
=> "12"

# all ids should be present -- confirmed
ids.each { |d| puts "INCLUDE #{d}?: #{bf.include?(d)}" }

INCLUDE 7a90b81e-9f21-47d2-a9f7-8533c8537e54?: true
INCLUDE 5b1ded55-f662-4fe7-822e-ba955e04503a?: true
INCLUDE 78ebf0f1-d8fc-4e35-9e07-9a25ef25e850?: true
INCLUDE 6070dc01-1a6d-4f35-b114-48e0ff92b61c?: true
INCLUDE 1d4b6147-c972-4433-a728-5b14f3c8b61b?: true
INCLUDE 7d1d4fc2-4137-4fba-9329-9f743a9f8a5b?: true
INCLUDE 9f76d6ff-6ca2-4a3c-a250-21dc13ffa712?: true
INCLUDE 9fdfa9d7-0c2a-4dfe-964e-7459f67eec0b?: true
INCLUDE 0674efdd-1111-4273-9927-4375656ee045?: true
INCLUDE ccb48632-1430-490b-a196-5a5da27f545d?: true
INCLUDE 43817598-7a16-40b1-a78b-881efd736576?: true
INCLUDE dacc26f9-40a4-4efd-be6c-09b3ed910b78?: true

# remove the first id, which we assume is written in bucket 1
[18] pry(main)> bf.remove(ids.first)
=> nil

# our write-to-latest theory is that it won't actually flip the bits in the first bucket -- confirmed
[19] pry(main)> bf.include?(ids.first)
=> true

# but we will increment count -- bloating the index calculation
[20] pry(main)> $redis.get("test:count")
=> "13"

# run an include check to see if one removal was enough to corrupt data in bucket 2 -- confirmed
ids.each { |d| puts "INCLUDE #{d}?: #{bf.include?(d)}" }

INCLUDE 7a90b81e-9f21-47d2-a9f7-8533c8537e54?: true
INCLUDE 5b1ded55-f662-4fe7-822e-ba955e04503a?: true
INCLUDE 78ebf0f1-d8fc-4e35-9e07-9a25ef25e850?: true
INCLUDE 6070dc01-1a6d-4f35-b114-48e0ff92b61c?: true
INCLUDE 1d4b6147-c972-4433-a728-5b14f3c8b61b?: true
INCLUDE 7d1d4fc2-4137-4fba-9329-9f743a9f8a5b?: true
INCLUDE 9f76d6ff-6ca2-4a3c-a250-21dc13ffa712?: true
INCLUDE 9fdfa9d7-0c2a-4dfe-964e-7459f67eec0b?: true
INCLUDE 0674efdd-1111-4273-9927-4375656ee045?: true
INCLUDE ccb48632-1430-490b-a196-5a5da27f545d?: true
INCLUDE 43817598-7a16-40b1-a78b-881efd736576?: true
INCLUDE dacc26f9-40a4-4efd-be6c-09b3ed910b78?: false

# clean-up the key
bf.clear
```

**So I think for safety, you should remove the `remove` calls.**

A nice update might be to implement [something like this](https://github.com/erikdubbelboer/redis-lua-scaling-bloom-filter/blob/master/add.lua#L48) from the original repo where we only increment the counter if the data isn't already present. Of course, checking all the related keys would be the most thorough way to do this, but probably at the cost of performance of a full check before each insert.

Let me know if I can help with the actual implementation if this is an update you're interested in making.

Our workaround for now is removing the `remove` calls in our calling code and doing a check-before-insert each time.

**Comment by taganaka** [comment]
@dankleiman  Thank you for your report. 
I agree the remove method is unsafe/not-supported and should be removed.

**Comment by taganaka** [comment]
Version 1.0.0 pushed to rubygems

**Comment by dankleiman** [comment]
Thanks @taganaka that's great!
