### ISSUE TITLE
Hiredis Dependency

### ISSUE THREAD

**Issue by dmcinnes** [taganaka/redis-bloomfilter#8]
Since it's a transport mechanism any reason why the hiredis dependency is required?
We are unfortunately in a situation were we can't use it for various reasons.

**Comment by taganaka** [comment]
This is a good point. hiredis was added mainly for performance reasons. I Agree this dependency should not required

**Comment by taganaka** [comment]
Addressed here: https://github.com/taganaka/redis-bloomfilter/pull/9

**Comment by dmcinnes** [comment]
Awesome, thanks!
